ecomapp/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import contact,index,about,signup
from .forms import LoginForm

app_name='core'
urlpatterns=[
    path('',index,name='index'),
    path('contact/',contact,name='contact'),
    path('about/',about,name='about'),
    path('signup/',signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login')
]

ecomapp/coversation/urls.py
from django.urls import path
from . import views

app_name='conversation'
urlpatterns = [
    path('',views.inbox,name='inbox'),
    path('new/<int:item_pk>/',views.new_conversation,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
]

ecomapp/dashboard/urls.py
from django.urls import path
from . import views

app_name='dashboard'

urlpatterns = [
    path('',views.dash,name='dash'),
]

ecomapp/ecomapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('core.urls')),
    path('coversation/',include('coversation.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('items/',include('item.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/item/urls.py
from django.urls import path
from . import views

app_name='item'
urlpatterns = [
    path('', views.items,name='item'),
    path('<int:pk>/',views.detail,name='detail'),
    path('new/', views.new,name='new'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
]

ecomapp/core/models.py
from django.db import models

# Create your models here.

ecomapp/core/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Your Username','class':'w-full px-6 py-6 rounded-xl'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Your Password','class':'w-full px-6 py-6 rounded-xl'})) 

class SignupForm(UserCreationForm):
     class Meta:
         model=User
         fields=('username','email','password1','password2')
         
     username=forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Your Username','class':'w-full px-6 py-6 rounded-xl'}))
     email=forms.CharField(widget=forms.EmailInput(attrs={'placeholder':'Your email','class':'w-full px-6 py-6 rounded-xl'}))
     password1=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Your Password','class':'w-full px-6 py-6 rounded-xl'}))
     password2=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Type Password again','class':'w-full px-6 py-6 rounded-xl'}))
         

ecomapp/core/views.py
from django.shortcuts import redirect, render
from item.models import Category,Item
from django.contrib.auth.admin import User
from .forms import SignupForm


# Create your views here.
def index(request):
    items=Item.objects.filter(is_sold=False)
    categories=Category.objects.all
    user_name=request.user.username
    return render(request,'core\index.html',{'items':items,'categories':categories,'username':user_name})

def contact(request):
    return render(request,'core\contact.html')

def about(request):
    return render(request,'core/about.html')

def signup(request):
    if request.method=='POST':
        signupForm=SignupForm(request.POST)
        if signupForm.is_valid:
            signupForm.save()
            return redirect('login/')
    else:
        signupForm=SignupForm()
    
    return render(request,'core/signup.html',{'signupForm':signupForm})
    
    
    

ecomapp/core/templates/core/about.html
{% extends "core\base.html" %}
{% block title %}About{% endblock %}
{% block content %}
<div class= ' px-3 py-3 rounded-xl bg-gray  text-teal-700'>
    <div class='mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl'>
    <h1 class='text-bold'> <strong>About</strong> </h1>
    <p class='text-semibold text-teal-400'> we believe in the joy of discovery and the excitement of finding unique, high-quality products that add a touch of magic to everyday life. Our online marketplace is designed to be your go-to destination for a seamless and delightful shopping experience.</p>
    </div>
    <div class='mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl'>
    <h1 class='text-bold'><strong> Our Story </strong></h1>
    <p class='text-semibold text-teal-400'>Founded 2020, E com app was born out of a passion for connecting people with a curated selection of exceptional products. What started as a vision has now evolved into a thriving platform that brings together a diverse range of sellers and buyers from around the world.</p>
    </div>
    <div class='mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl'>
        <h1 class='text-bold'><strong> Our Mission </strong></h1>
    <p class='text-semibold text-teal-400'> We are on a mission to redefine online shopping by offering a thoughtfully curated collection of products that combine style, quality, and affordability. With a commitment to customer satisfaction, we strive to make every purchase a rewarding and enjoyable experience.</p>
    </div>
    <div class='mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl'>
        <h1 class='text-bold text-teal-700'><strong> Why Choose us</strong> </h1>  
     <ul class='text-teal-500'>
            <li><strong>Curated Selection:</strong>
                <p>Our team scours the globe to bring you a curated selection of products that meet our high standards for quality and innovation.</p>
            </li>
            <li><strong>Customer-Centric Approach:</strong>
                <p>Your satisfaction is our priority. We are dedicated to providing excellent customer service and support at every step of your shopping journey.</p>
            </li>
            <li><strong>Secure and Convenient:</strong>
                <p>Shop with confidence knowing that your transactions are secure, and our user-friendly platform makes your shopping experience hassle-free</p>
            </li>
        </ul> 
    </div>
    <div class='mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl'>
        <h1 class='text-bold'> <strong>Join Our Community</strong> </h1>
    <p class='text-semibold text-teal-400'> Become a part of the E Com App community! Follow us on social media, sign up for our newsletter, and stay updated on the latest trends, promotions, and product launches.</p>
    </div>
 
{% endblock%}

ecomapp/core/templates/core/base.html
<!Doctype html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1.0'>
        <script src='https://cdn.tailwindcss.com'></script>
        <title> {% block title%}{% endblock%}</title>
        <body>
            <div class='px-6 py-6'>
             
              <nav class='py-6 flex justify-between item-center border-b border-gray-200'>
                <a href='/' class='text-3xl font-semibold'> E Comm App </a>
                <div class='space-x-6'>
                    <a href='{% url 'item:new' %}' class='text-lg font-semibold hover:text-gray-500'> New Item</a>
                    <a href='{% url 'item:item' %}' class='text-lg font-semibold hover:text-gray-500'> Browse</a>
                    {% if request.user.is_authenticated %}
                    <a href='{% url 'conversation:inbox' %}' class='px-6 py-3 text-md font-semibold bg-teal-500 text-white rounded-lg hover:bg-teal-700'>Inbox</a>
                    <a href='{% url 'dashboard:dash' %}' class='px-6 py-3 text-md  font-semibold bg-gray-500 text-white rounded-lg hover:bg-gray-700'>Dashboard</a>
                    {% else %}
                    <a href='{% url 'core:signup' %}' class='px-6 py-3 text-md font-semibold bg-teal-500 text-white rounded-lg hover:bg-teal-700'>Sign Up</a>
                    <a href='{% url 'core:login' %}' class='px-6 py-3 text-md  font-semibold bg-gray-500 text-white rounded-lg hover:bg-gray-700'>Login</a>
                {% endif %}
                </div>
            </nav>
            {% block content %}
            {% endblock %} 
            <footer class="py-6 px-6 flex justify-between bg-gray-800 rounded-lg">
                <div class='w-2/3 pr=10'>
                    <h3 class="mb-5 font-semibold text-gray-400"> About</h3>
                    <p class='text=lg text-gray-700'> Lorem opsum bla ba bla.... Lorem opsum bla ba bla....</p>
                </div>
                <div class='w-1/3 '>
                    <h3 class="mb-5 font-semibold text-gray-400"> Menu</h3>
                    <ul class="space-y-2">
                        <li> <a href='{% url 'core:about' %}' class='text-lg text-teal-500 hover:text-teal-700'>About</a></li>
                        <li> <a href='{% url 'core:contact' %}' class='text-lg text-teal-500 hover:text-teal-700'>Contact</a></li>
                        <li> <a href='#' class='text-lg text-teal-500 hover:text-teal-700'>Privacy Policy</a></li>
                        <li> <a href='#' class='text-lg text-teal-500 hover:text-teal-700'>Term of use</a></li>
                </div>

            </footer>
        </body>
    </html>

ecomapp/core/templates/core/contact.html
{% extends "core\base.html" %}
{% block title %}hello welcome to contact page{% endblock%}
{% block content %} 
<h1> Contact Page</h1>
<p>Hi there...You arrived to contacts page</p>

{% endblock %}

ecomapp/core/templates/core/index.html
{% extends "core\base.html" %}
{% block title %}hello welcome {{username}}{% endblock%}
{% block content %} 
<div class='mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl'>
    <h2 class='mb-12 text-2xl text-center'>Newest Items</h2>

<div class='grid grid-cols-3 gap-3'>
    {% for item in items%}
    <div>
        <a href='{%url 'item:detail' item.id %}'>
    <div>   
        <img src='{{ item.image.url }}' class='rounded-xl w-60 h-60'>
    </div>
    <div class='p-6 bg-white rounded-b-xl'>
        <h2 class='text-2xl'>{{item.name}}</h2>
        <p class='text-gray-500'>Price:{{item.price}}</p>
        {% if item.description %}
        <p class='text-gray-500'>Description:{{item.description}}</p>
        {% endif %}
    </div>
        </a>
    
    </div>

    {% endfor %}
</div>
</div>
<div class='mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl'>
    <h2 class='mb-12 text-2xl text-center'> Categories</h2>

<div class='grid grid-cols-3 gap-3'>
    {% for category in categories%}
    
    <div class='p-6 bg-white rounded-b-xl'>
        <h2 class='text-2xl'>{{category.name}}</h2>
        <p class='text-gray-500'>{{category.items.count}} items</p>
    
    
    </div>

    {% endfor %}
</div>
</div>
{% endblock %}

ecomapp/core/templates/core/login.html
{% extends 'core\base.html' %}
{% block title %} Login{% endblock%}
{% block content %}
<div class='my-6 mx-3 px-6 py-6 rounded-xl bg-gray-100 w-1/2'>
    <h1 class='mb-x text-3xl'> Login</h1>
    <form method='post' action='.'>
        {% csrf_token %}
        <div class='mt-3 mb-3'>
            <label class='inline-block mb-2'>User Name</label></br>
            {{ form.username }}
        </div>
        <div class='mb-3'>
            <label class='inline-block mb-2'>Password</label></br>
            {{form.password}}
        </div>
    {% if form.error or form.non_field_errors  %}
        <div class='mb-3 p-6 rounded-xl bg-red-700'>
            {% for field in form %}
            {{ field.error }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %} 
      
            <button class='py-4 px-8 text-md  bg-teal-500 rounded-xl hover:bg-teal-700'>submit</button>
           
           
    </form>
</div>
{% endblock %}

ecomapp/core/templates/core/signup.html
{% extends 'core\base.html' %}
{% block title %} Signup{% endblock%}
{% block content %}
<div class='my-6 mx-3 px-6 py-6 rounded-xl bg-gray-100 w-1/2'>
    <h1 class='mb-x text-3xl'> Signup</h1>
    <form method='post' action='.'>
        {% csrf_token %}
        <div class='mt-3 mb-3'>
            <label class='inline-block mb-2'>User Name</label></br>
            {{ signupForm.username }}
        </div>
        <div class='mb-3'>
            <label class='inline-block mb-2'>Email</label></br>
            {{signupForm.email}}
        </div>
        <div class='mb-3'>
            <label class='inline-block mb-2'>Password</label></br>
            {{signupForm.password1}}
        </div>
        <div class='mb-3'>
            <label class='inline-block mb-2'>Confirm Password</label></br>
            {{signupForm.password2}}
        </div>
    {% if signupForm.error or signupForm.non_field_errors  %}
        <div class='mb-3 p-6 rounded-xl bg-red-700'>
            {% for field in signupForm %}
            {{ field.error }}
            {% endfor %}
            {{ signupForm.non_field_errors }}
        </div>
        {% endif %} 
      
            <button class='py-4 px-8 text-md  bg-teal-500 rounded-xl hover:bg-teal-700'>submit</button>
           
           
    </form>
</div>
{% endblock %}