ecomapp/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import contact,index,about,signup
from .forms import LoginForm

app_name='core'
urlpatterns=[
    path('',index,name='index'),
    path('contact/',contact,name='contact'),
    path('about/',about,name='about'),
    path('signup/',signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm),name='login')
]

ecomapp/coversation/urls.py
from django.urls import path
from . import views

app_name='conversation'
urlpatterns = [
    path('',views.inbox,name='inbox'),
    path('new/<int:item_pk>/',views.new_conversation,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
]

ecomapp/ecomapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('core.urls')),
    path('coversation/',include('coversation.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('items/',include('item.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/item/urls.py
from django.urls import path
from . import views

app_name='item'
urlpatterns = [
    path('', views.items,name='item'),
    path('<int:pk>/',views.detail,name='detail'),
    path('new/', views.new,name='new'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
]

ecomapp/item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category (models.Model):
    name=models.CharField( max_length=255)
    
    class Meta:
        ordering=()
        verbose_name_plural='Categories'
    
    def __str__(self):
        return self.name
    

class Item(models.Model):
    category=models.ForeignKey(Category,related_name='items', on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    description=models.TextField(null=True,blank=True)
    image=models.ImageField(upload_to='upload_images', blank=True,null=True)
    price=models.FloatField()
    is_sold=models.BooleanField(default=False)
    created_by=models.ForeignKey(User,related_name='items', on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    
    def __str__(self) :
        return self.name
    
    

ecomapp/item/forms.py
from django import forms 
from .models import Item

INPUT_CLASS='w-full px-6 py-3 rounded-xl'
class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category','name','description','image','price')
        widgets={
            'category':forms.Select(attrs={
                'class':INPUT_CLASS
            }),
            'name':forms.TextInput(attrs={
                'class':INPUT_CLASS
            }),
            'description':forms.Textarea(attrs={
                'class':INPUT_CLASS
            }),
            'image':forms.FileInput(attrs={
                'class':INPUT_CLASS
            }),
            'price':forms.TextInput(attrs={
                'class':INPUT_CLASS
            }),
           
            
            
        }
        
class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name','description','image','price','is_sold')
        widgets={
            'name':forms.TextInput(attrs={
                'class':INPUT_CLASS
            }),
            'description':forms.Textarea(attrs={
                'class':INPUT_CLASS
            }),
            'image':forms.FileInput(attrs={
                'class':INPUT_CLASS
            }),
            'price':forms.TextInput(attrs={
                'class':INPUT_CLASS
            }),
           
            
            
        }
    

ecomapp/item/views.py
from django.shortcuts import redirect, render,get_object_or_404
from .forms import NewItemForm,EditItemForm
from .models import Item,Category
from django.contrib.auth.decorators import login_required
from django.db.models import Q


def items(request):
    query= request.GET.get('query','')
    category_id= request.GET.get('category',0)
    item_price=request.GET.get('price',0)
    categories=Category.objects.all()
    items=Item.objects.filter(is_sold=False)
    item_price=int(item_price)
    if item_price:
        if item_price>100:
            items=items.filter(price__gte=100)
        else:
           items=items.filter(price__lt=100) 
    if category_id:
        items=items.filter( category_id=category_id)
    if query:
        items=items.filter( Q(name__icontains=query)| Q( description__icontains=query))
    return render(request,'item/item.html',{'items':items,'query':query,'categories':categories,'category_id':int(category_id),'item_price':int(item_price)})

def detail(request,pk):
    item=get_object_or_404(Item,pk=pk)
    related_items=Item.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)
    return render(request,'item\detail.html',{'item':item,'related_items':related_items})

@login_required
def new(request):
    if request.method=='POST':
        form=NewItemForm(request.POST,request.FILES)
        if form.is_valid():  
           item=form.save(commit=False)
           item.created_by=request.user
           item.save()
           return redirect('item:detail',pk=item.id)
    else:
        form= NewItemForm()
    return render(request,'item/form.html',{'form':form,'title':'New Item'})

@login_required
def delete(request,pk):
    item=get_object_or_404(Item,pk=pk,created_by=request.user)
    item.delete()
    return redirect('dashboard:dash')


@login_required
def edit(request,pk):
    item=get_object_or_404(Item,pk=pk,created_by=request.user)
    if request.method=='POST':
        form=EditItemForm(request.POST,request.FILES,instance=item)
        
        if form.is_valid():   
           form.save()
           
           return redirect('item:detail',pk=item.id)
    else:
        form= EditItemForm(instance=item)
    return render(request,'item/form.html',{'form':form,'title':'Edit Item'})

ecomapp/item/templates/item/detail.html
{% extends 'core\base.html' %}
{% block title%}{{item.name}}{% endblock %}
{% block content %}
<div class='grid grid-cols-5 rounded-lg mt-6 mb-6'>
    
    <div class='col-span-3  h-60'>
        <img src='{{item.image.url}}' class='w-full h-full rounded-xl px-8'>    
    </div>
    <div class='col-span-2 p-6 rounded-xl bg-gray-200 gap-6'>
        <h1><strong>{{item.name}}</strong></h1>
        {% if item.description %}
        <h2> Description:{{item.description}}</h2>
        {% endif %}
        <h2>Price: {{item.price}}</h2>
        <h2>Created By: {{item.created_by}}</h2>
        {% if request.user == item.created_by %}
        <div class='mt-6 p-6 bg-white rounded-xl'>
            <p> This is your item!  </p>
            <a href='{% url 'item:edit' item.id %}' class='inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl'>Edit</a>
            <a href='{% url 'item:delete' item.id %}' class='inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl'>Delete</a>
            </div>
        {% else %}
        <a href='{% url 'conversation:new' item.id %}' class='inline-block mt-6 px-6 py-3 font-semibold text-white bg-teal-500 hover:bg-teal-800 rounded-xl px-6'>Contact Seller</a>
        {% endif %}
    </div>
</div>

<div class='mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl'>
    <h2 class='mb-12 text-2xl text-center'>Related Items</h2>

<div class='grid grid-cols-3 gap-3'>
    {% for item in related_items%}
    <div>
        <a href='{%url 'item:detail' item.id %}'>
    <div>   
        <img src='{{ item.image.url }}' class='rounded-xl w-60 h-60'>
    </div>
    <div class='p-6 bg-white rounded-b-xl'>
        <h2 class='text-2xl'>{{item.name}}</h2>
        <p class='text-gray-500'>Price:{{item.price}}</p>
        {% if item.description %}
        <p class='text-gray-500'>Description:{{item.description}}</p>
        {% endif %}
    </div>
        </a>
    
    </div>

    {% endfor %}
</div>
</div>

{% endblock %} 

ecomapp/item/templates/item/form.html
{% extends 'core/base.html' %}
{% block title %} {{title}} {% endblock %}
{% block content %}
<h1 class='mb-6 text-2xl font-semibold mt-3'> {{title}} </h1>
<form method='POST' action='.' enctype='multipart/form-data'>
    {% csrf_token %}
    <div class=''>
        {{form.as_p}}
    </div>
    {% if form.error or form.non_field_errors  %}
        <div class='mb-3 p-6 rounded-xl bg-red-700'>
            {% for field in form %}
            {{ field.error }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <button class='py-4 px-8 text-md  bg-teal-500 rounded-xl hover:bg-teal-700 mt-3 mb-6'>submit</button>
    </form>
    {% endblock %}

ecomapp/item/templates/item/item.html
{% extends 'core/base.html'%}
{% block title %}Browse {% endblock%}
{% block content %}
<div class='pb-6 grid grid-cols-4 gap-4 bg-gray-100'>
    <div class='col-span-1'>
        <form method='GET' action='{% url 'item:item'%}?query={{query}}  %}'>
            <input name='query' class='w-full py-4 px-6 border rounded-xl' type='text' value='{{query}}' placeholder='Find a furniture ,cloth or a toy'>
        <button class='mt-2 py-4 px-8 text-lg bg-teal-500 rounded-xl text-white '>Search</button>
        </form>
        <hr class='my-6'>
        <p class='font-semibold'>Categories</p>
        <ul>
        {% for category in categories %}
        <li class='py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %}'>
            <a href='{% url 'item:item'%}?query={{query}}&category={{category.id}}'>{{category.name}}</a>
            <a href='{% url 'item:item'%}?query={{query}}&category={{category.id}}&price=200'>above 100</a>
            <a href='{% url 'item:item'%}?query={{query}}&category={{category.id}}&price=50'>below 100</a>
            </li>
            {% endfor %}
        </ul>  
        <hr class='my-6'>
        <p class='font-semibold'>Clear Filters</p>  
        <ul>
            <li><a href='{% url 'item:item' %}' class='mt-2 py-4 px-8 rounded-xl bg-yellow-500 inline-block text-lg text-white '>Clear</a></li>
        </ul>
        </div>
    <div class='col-span-3'>
        <div class='grid grid-cols-3 gap-3'>
            {% for item in items%}
            <div>
                <a href='{%url 'item:detail' item.id %}'>
            <div>   
                <img src='{{ item.image.url }}' class='rounded-xl w-60 h-60'>
            </div>
            <div class='p-6 bg-white rounded-b-xl'>
                <h2 class='text-2xl'>{{item.name}}</h2>
                <p class='text-gray-500'>Price:{{item.price}}</p>
                {% if item.description %}
                <p class='text-gray-500'>Description:{{item.description}}</p>
                {% endif %}
            </div>
                </a>
            
            </div>
        
            {% endfor %}
        </div>
        </div>
    </div>
        
{% endblock %}